version: '3.5'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
      - "1080:80"
    volumes:
      - ./docker/nginx/etc:/etc/nginx/conf.d:cached,ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:cached,ro
    restart: always
    networks:
      default:
        aliases:
          - "mockserver.lightningdev.com"
  mockserver:
    image: jamesdbloom/mockserver
    entrypoint:
      - /opt/mockserver/run_mockserver.sh
      - -serverPort
      - "80,443"
#      - -jvmOptions
#      - -Dmockserver.initializationJsonPath="/opt/mockserver/init/initializerJson.json"
#      - -Dmockserver.sslSubjectAlternativeNameDomains="mockserver,api.externalservice.com"
    user: root
#    environment:
#      - LOG_LEVEL=ERROR
    volumes:
      - ./mockserver/initializerJson.json:/opt/mockserver/init/initializerJson.json
#    networks:
#      default:
#        aliases:
#          - "api.externalservice.com"