version: '3.5'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
      - "1080:80"
    volumes:
      - ./docker/nginx/etc:/etc/nginx/conf.d:cached,ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:cached,ro
    restart: always
    depends_on:
      - app
      - mockserver
    networks:
      default:
        aliases:
          - "mockserver.lightningdev.com"
  app:
    image: php:7-apache
    volumes:
      - ./app/public:/var/www/html/:cached
      - ./mockserver/CertificateAuthorityCertificate.pem:/etc/ssl/certs/mockserver.pem
      - ./mockserver/curl-ca.crt:/etc/ssl/certs/ca-certificates.crt
  mockserver:
    image: jamesdbloom/mockserver
    entrypoint:
      - /opt/mockserver/run_mockserver.sh
      - -serverPort
      - "80,443"
#      - -jvmOptions
#      - -Dmockserver.initializationJsonPath="/opt/mockserver/init/initializerJson.json"
#      - -Dmockserver.sslSubjectAlternativeNameDomains="mockserver,api.ipify.org"
    user: root
#    environment:
#      - LOG_LEVEL=ERROR
    volumes:
      - ./mockserver/initializerJson.json:/opt/mockserver/init/initializerJson.json
      - ./mockserver/resolv.conf:/etc/resolv.conf:ro
#    networks:
#      default:
#        aliases:
#          - "api.ipify.org"